test: 🚨tested git hook
Implemented a new git hook validation to check the branch name.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,11 +3,12 @@
 
 BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
 MAIN_PATTERN_NAME="^(development|production|staging)$"
+FEATURE_PATTERN_NAME="^(feat|refactor|fix)/TIC-[0-9]{1,4}$"
 ERROR_MESSAGE="ERROR: The branch name does not follow the required pattern ([feat | refactor | fix]/TIC-NUMBER)."
 
-if [[ ! "$BRANCH_NAME" =~ $MAIN_PATTERN_NAME ]]; then
-  echo "${ERROR_MESSAGE}"
-  exit 1
+if [[ ! "$BRANCH_NAME" =~ $MAIN_PATTERN_NAME ]] || [[ ! "$BRANCH_NAME" =~ $FEATURE_PATTERN_NAME ]]; then
+  exit 0
 fi
 
-exit 0
+echo "${ERROR_MESSAGE}"
+exit 1
