test: 🚨tested git hook
Implemented a new git hook validation to check the branch name.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -4,11 +4,19 @@
 BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
 MAIN_PATTERN_NAME="^(development|production|staging)$"
 FEATURE_PATTERN_NAME="^(feat|refactor|fix)/TIC-[0-9]{1,4}$"
-ERROR_MESSAGE="ERROR: The branch name does not follow the required pattern ([feat | refactor | fix]/TIC-NUMBER)."
 
-if [[ ! "$BRANCH_NAME" =~ $MAIN_PATTERN_NAME ]] || [[ ! "$BRANCH_NAME" =~ $FEATURE_PATTERN_NAME ]]; then
+if [[ "$BRANCH_NAME" =~ $MAIN_PATTERN_NAME ]] || [[ "$BRANCH_NAME" =~ $FEATURE_PATTERN_NAME ]]; then
   exit 0
 fi
 
-echo "${ERROR_MESSAGE}"
+if [[ ! "$BRANCH_NAME" =~ MAIN_PATTERN_NAME ]]; then
+  echo "ERROR: The branch name does not follow the required pattern (development|production|staging)."
+  exit 1
+fi
+
+if [[ ! "$BRANCH_NAME" =~ $FEATURE_PATTERN_NAME ]]; then
+  echo "ERROR: The branch name does not follow the required pattern ([feat | refactor | fix]/TIC-NUMBER)."
+  exit 1
+fi
+
 exit 1
